export const NEWS_SOURCES: { [key: string]: { logo: string } } = {
    'BBC Sport': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/BBC_Sport_2019.svg/1200px-BBC_Sport_2019.svg.png' },
    'Sky Sports': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Sky_Sports_logo.svg/1200px-Sky_Sports_logo.svg.png' },
    'ESPN': { logo: 'https://a.espncdn.com/i/espn/espn_logos/espn_red.png' },
    'NBC Sports': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/NBC_Sports_logo.svg/1200px-NBC_Sports_logo.svg.png' },
    'BeIN Sports': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/BeIN_Sports_logo.svg/1200px-BeIN_Sports_logo.svg.png' },
    'Goal.com': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Goal.com_logo.svg/1200px-Goal.com_logo.svg.png' },
    'The False 9': { logo: 'https://thefalse9.com/wp-content/uploads/2019/01/cropped-false9_logo_light-300x300.png' },
    'Football365': { logo: 'https://www.football365.com/wp-content/uploads/2020/01/f365-logo-new.png' },
    'talkSPORT': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/TalkSport_logo.svg/1200px-TalkSport_logo.svg.png' },
    'GiveMeSport': { logo: 'https://www.givemesport.com/static/uploads/2020/06/gms-logo.png' },
    'FourFourTwo': { logo: 'https://cdn.mos.cms.futurecdn.net/6bKwKpnEjGjfDGKHFk7nJV-300-80.png' },
    'TalkSport Football': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/TalkSport_logo.svg/1200px-TalkSport_logo.svg.png' },
    'The Athletic': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/The_Athletic_logo.svg/1200px-The_Athletic_logo.svg.png' },
    'Transfermarkt': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Transfermarkt_logo.svg/1200px-Transfermarkt_logo.svg.png' },
    'Football Italia': { logo: 'https://www.football-italia.net/sites/all/themes/football_italia/logo.png' },
    'Marca': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Marca.svg/1200px-Marca.svg.png' },
    'Sport.es': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Sport_logo.svg/1200px-Sport_logo.svg.png' },
    'Mundo Deportivo': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Mundo_Deportivo_logo.svg/1200px-Mundo_Deportivo_logo.svg.png' },
    'Football London': { logo: 'https://i2-prod.football.london/incoming/article18965937.ece/ALTERNATES/s1200/0_FL-LOGO.png' },
    '90min': { logo: 'https://images.90min.com/production/90min-logo-white.png' },
    'CNN Sports': { logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/CNN_International_logo.svg/1200px-CNN_International_logo.svg.png' },
};
