# Cloudflare Pages configuration
name = "fixturecast"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

[env.production]
[[env.production.kv_namespaces]]
binding = "PREDICTIONS_KV"
id = "f00e18bfc6a44f3d876bd4448003e1f5"
preview_id = "f00e18bfc6a44f3d876bd4448003e1f5"

# Note: Set PREDICTION_API_KEY (and optionally VITE_PREDICTION_API_KEY) in the Pages dashboard