name = "fixturecast-cron-worker"
main = "worker.js"
compatibility_date = "2024-01-15"

[[kv_namespaces]]
binding = "PREDICTIONS_KV"
# Use the same namespace ID as Pages (update if different in Cloudflare dashboard)
id = "f00e18bfc6a44f3d876bd4448003e1f5"
preview_id = "f00e18bfc6a44f3d876bd4448003e1f5"

# Cron Triggers (UK-friendly times)
[triggers]
crons = [
  "0 6,12,18,23 * * *",  # 07:00, 13:00, 19:00, 00:00 London time (BST)
  "15 * * * *"           # Every hour at 15 minutes past - Update scores
]

# Environment Variables
[vars]
FIXTURECAST_DOMAIN = "https://fixturecast.pages.dev"

# Secrets (set via CLI or dashboard)
# wrangler secret put PREDICTION_API_KEY
# wrangler secret put ERROR_WEBHOOK_URL (optional)

# Production environment
[env.production.vars]
FIXTURECAST_DOMAIN = "https://fixturecast.com"