name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit --pretty false

      - name: Unit tests
        run: npm run test:run

  preview:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy-preview:
    if: ${{ github.event_name == 'pull_request' }}
    needs: preview
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages (preview)
        uses: actions/deploy-pages@v4

  lighthouse:
    if: ${{ github.event_name == 'pull_request' }}
    needs: deploy-preview
    runs-on: ubuntu-latest
    steps:
      - name: Install Lighthouse CI
        run: |
          npm i -g @lhci/cli@0.13.x
      - name: Run Lighthouse CI against preview
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          # Replace with your preview URL if not using GitHub Pages
          PREVIEW_URL=${{ steps.deployment.outputs.page_url || 'http://localhost:4173' }}
          echo "Preview: $PREVIEW_URL"
          lhci autorun --collect.url=$PREVIEW_URL --upload.target=temporary-public-storage || echo "LHCI failed but not blocking"


